// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: channels.sql

package queries

import (
	"context"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (user_id, name, stream_key_hash)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, title, stream_key_hash, created_at
`

type CreateChannelParams struct {
	UserID        int64
	Name          string
	StreamKeyHash string
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel, arg.UserID, arg.Name, arg.StreamKeyHash)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Title,
		&i.StreamKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelByName = `-- name: GetChannelByName :one
SELECT id, user_id, name, title, stream_key_hash, created_at FROM channels WHERE name = $1
`

func (q *Queries) GetChannelByName(ctx context.Context, name string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByName, name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Title,
		&i.StreamKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelByStreamKeyHash = `-- name: GetChannelByStreamKeyHash :one
SELECT id, user_id, name, title, stream_key_hash, created_at FROM channels WHERE stream_key_hash = $1
`

func (q *Queries) GetChannelByStreamKeyHash(ctx context.Context, streamKeyHash string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByStreamKeyHash, streamKeyHash)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Title,
		&i.StreamKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelByUserID = `-- name: GetChannelByUserID :one
SELECT id, user_id, name, title, stream_key_hash, created_at FROM channels WHERE user_id = $1
`

func (q *Queries) GetChannelByUserID(ctx context.Context, userID int64) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByUserID, userID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Title,
		&i.StreamKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const updateChannelStreamKey = `-- name: UpdateChannelStreamKey :exec
UPDATE channels SET stream_key_hash = $2 WHERE id = $1
`

type UpdateChannelStreamKeyParams struct {
	ID            int64
	StreamKeyHash string
}

func (q *Queries) UpdateChannelStreamKey(ctx context.Context, arg UpdateChannelStreamKeyParams) error {
	_, err := q.db.Exec(ctx, updateChannelStreamKey, arg.ID, arg.StreamKeyHash)
	return err
}

const updateChannelTitle = `-- name: UpdateChannelTitle :exec
UPDATE channels SET title = $2 WHERE id = $1
`

type UpdateChannelTitleParams struct {
	ID    int64
	Title string
}

func (q *Queries) UpdateChannelTitle(ctx context.Context, arg UpdateChannelTitleParams) error {
	_, err := q.db.Exec(ctx, updateChannelTitle, arg.ID, arg.Title)
	return err
}
