// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID            int64
	UserID        int64
	Name          string
	Title         string
	StreamKeyHash string
	CreatedAt     pgtype.Timestamptz
}

type Session struct {
	ID        string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type StreamSession struct {
	ID        int64
	ChannelID int64
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
	EndReason *string
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
