// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	ID        string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT
    s.id           AS session_id,
    s.expires_at   AS session_expires_at,
    u.id           AS user_id,
    u.username     AS user_username,
    u.email        AS user_email,
    u.password_hash AS user_password_hash,
    u.created_at   AS user_created_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1 AND s.expires_at > now()
`

type GetSessionWithUserRow struct {
	SessionID        string
	SessionExpiresAt pgtype.Timestamptz
	UserID           int64
	UserUsername     string
	UserEmail        string
	UserPasswordHash string
	UserCreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetSessionWithUser(ctx context.Context, id string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, id)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.SessionID,
		&i.SessionExpiresAt,
		&i.UserID,
		&i.UserUsername,
		&i.UserEmail,
		&i.UserPasswordHash,
		&i.UserCreatedAt,
	)
	return i, err
}
