// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: stream_sessions.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStreamSession = `-- name: CreateStreamSession :one
INSERT INTO stream_sessions (channel_id, started_at)
VALUES ($1, $2)
RETURNING id, channel_id, started_at, ended_at, end_reason
`

type CreateStreamSessionParams struct {
	ChannelID int64
	StartedAt pgtype.Timestamptz
}

func (q *Queries) CreateStreamSession(ctx context.Context, arg CreateStreamSessionParams) (StreamSession, error) {
	row := q.db.QueryRow(ctx, createStreamSession, arg.ChannelID, arg.StartedAt)
	var i StreamSession
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const endStreamSession = `-- name: EndStreamSession :exec
UPDATE stream_sessions
SET ended_at  = $2,
    end_reason = $3
WHERE id = $1 AND ended_at IS NULL
`

type EndStreamSessionParams struct {
	ID        int64
	EndedAt   pgtype.Timestamptz
	EndReason *string
}

func (q *Queries) EndStreamSession(ctx context.Context, arg EndStreamSessionParams) error {
	_, err := q.db.Exec(ctx, endStreamSession, arg.ID, arg.EndedAt, arg.EndReason)
	return err
}

const markOpenStreamSessionsOrphaned = `-- name: MarkOpenStreamSessionsOrphaned :exec
UPDATE stream_sessions
SET ended_at  = now(),
    end_reason = 'orphan_swept'
WHERE ended_at IS NULL
`

func (q *Queries) MarkOpenStreamSessionsOrphaned(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markOpenStreamSessionsOrphaned)
	return err
}
